# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

push-image:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update --no-cache npm build-base python3 git
    - git clone https://$CONFIG_TOKEN_USERNAME:$CONFIG_TOKEN_VALUE@gitlab.com/wellfound/devcontainer-images/configuration-files.git
    - cp ./configuration-files/.pre-commit-config.yaml ./image/.devcontainer/.pre-commit-config.yaml
    - npm install -g @devcontainers/cli
    - devcontainer build --workspace-folder ./image/ --image-name $IMAGE_TAG
    - docker push $IMAGE_TAG
